import type { Qsear30PrdTraceRow } from '../types/Qsear30PrdTraceTypes';

export const createQsear30PrdTraceRow = (): Qsear30PrdTraceRow => {
  return {
    chk: '',
    testLot: '',
    lotCreateDate: '',
    orderNo: '',
    orderSeq: '',
    batchNo: '',
    prdLotNo: '',
    matrCiCode: '',
    matrCode: '',
    matrName: '',
    judgCode: '',
    strgQty: '',
    pacPdtqty: '',
    pacQty: '',
    hal3Pacqty: '',
    checkUserCmnt: '',
    pacDate: '',
    startTime: '',
    endTime: '',
    wrkCenter: '',
    wrkCenterName: '',
    wrkMan: '',
    remark: '',
    smlPresCode: '',
    pacSeq: '',
    microTestLot: '',
    microTestBarcode: '',
    btraTestResult1: '',
    btraTestResult2: '',
    btraTestResult3: '',
    finalTestResult: '',
    finalTestJudg: '',
    testCi: '',
    wrkOrderDate: '',
    hal3TestLot: '',
  };
};
