import type { UseQueryOptions } from '@tanstack/react-query';
import type { PagesRes } from '@/api/common';
type UsePageListOptions = Omit<UseQueryOptions<PagesRes, Error, PagesRes>, 'queryKey' | 'queryFn'> & {
    enabled?: boolean;
};
export declare const usePageList: (options?: UsePageListOptions) => {
    routes: import("@/routes/Routes").AppRoute[];
    isLoading: boolean;
    data: PagesRes;
    error: Error;
    isError: true;
    isPending: false;
    isLoadingError: false;
    isRefetchError: true;
    isSuccess: false;
    isPlaceholderData: false;
    status: "error";
    dataUpdatedAt: number;
    errorUpdatedAt: number;
    failureCount: number;
    failureReason: Error | null;
    errorUpdateCount: number;
    isFetched: boolean;
    isFetchedAfterMount: boolean;
    isFetching: boolean;
    isInitialLoading: boolean;
    isPaused: boolean;
    isRefetching: boolean;
    isStale: boolean;
    isEnabled: boolean;
    refetch: (options?: import("@tanstack/query-core").RefetchOptions) => Promise<import("@tanstack/query-core").QueryObserverResult<PagesRes, Error>>;
    fetchStatus: import("@tanstack/query-core").FetchStatus;
    promise: Promise<PagesRes>;
} | {
    routes: import("@/routes/Routes").AppRoute[];
    isLoading: boolean;
    data: PagesRes;
    error: null;
    isError: false;
    isPending: false;
    isLoadingError: false;
    isRefetchError: false;
    isSuccess: true;
    isPlaceholderData: false;
    status: "success";
    dataUpdatedAt: number;
    errorUpdatedAt: number;
    failureCount: number;
    failureReason: Error | null;
    errorUpdateCount: number;
    isFetched: boolean;
    isFetchedAfterMount: boolean;
    isFetching: boolean;
    isInitialLoading: boolean;
    isPaused: boolean;
    isRefetching: boolean;
    isStale: boolean;
    isEnabled: boolean;
    refetch: (options?: import("@tanstack/query-core").RefetchOptions) => Promise<import("@tanstack/query-core").QueryObserverResult<PagesRes, Error>>;
    fetchStatus: import("@tanstack/query-core").FetchStatus;
    promise: Promise<PagesRes>;
} | {
    routes: import("@/routes/Routes").AppRoute[];
    isLoading: boolean;
    data: undefined;
    error: Error;
    isError: true;
    isPending: false;
    isLoadingError: true;
    isRefetchError: false;
    isSuccess: false;
    isPlaceholderData: false;
    status: "error";
    dataUpdatedAt: number;
    errorUpdatedAt: number;
    failureCount: number;
    failureReason: Error | null;
    errorUpdateCount: number;
    isFetched: boolean;
    isFetchedAfterMount: boolean;
    isFetching: boolean;
    isInitialLoading: boolean;
    isPaused: boolean;
    isRefetching: boolean;
    isStale: boolean;
    isEnabled: boolean;
    refetch: (options?: import("@tanstack/query-core").RefetchOptions) => Promise<import("@tanstack/query-core").QueryObserverResult<PagesRes, Error>>;
    fetchStatus: import("@tanstack/query-core").FetchStatus;
    promise: Promise<PagesRes>;
} | {
    routes: import("@/routes/Routes").AppRoute[];
    isLoading: boolean;
    data: undefined;
    error: null;
    isError: false;
    isPending: true;
    isLoadingError: false;
    isRefetchError: false;
    isSuccess: false;
    isPlaceholderData: false;
    status: "pending";
    dataUpdatedAt: number;
    errorUpdatedAt: number;
    failureCount: number;
    failureReason: Error | null;
    errorUpdateCount: number;
    isFetched: boolean;
    isFetchedAfterMount: boolean;
    isFetching: boolean;
    isInitialLoading: boolean;
    isPaused: boolean;
    isRefetching: boolean;
    isStale: boolean;
    isEnabled: boolean;
    refetch: (options?: import("@tanstack/query-core").RefetchOptions) => Promise<import("@tanstack/query-core").QueryObserverResult<PagesRes, Error>>;
    fetchStatus: import("@tanstack/query-core").FetchStatus;
    promise: Promise<PagesRes>;
} | {
    routes: import("@/routes/Routes").AppRoute[];
    isLoading: boolean;
    data: undefined;
    error: null;
    isError: false;
    isPending: true;
    isLoadingError: false;
    isRefetchError: false;
    isSuccess: false;
    isPlaceholderData: false;
    status: "pending";
    dataUpdatedAt: number;
    errorUpdatedAt: number;
    failureCount: number;
    failureReason: Error | null;
    errorUpdateCount: number;
    isFetched: boolean;
    isFetchedAfterMount: boolean;
    isFetching: boolean;
    isInitialLoading: boolean;
    isPaused: boolean;
    isRefetching: boolean;
    isStale: boolean;
    isEnabled: boolean;
    refetch: (options?: import("@tanstack/query-core").RefetchOptions) => Promise<import("@tanstack/query-core").QueryObserverResult<PagesRes, Error>>;
    fetchStatus: import("@tanstack/query-core").FetchStatus;
    promise: Promise<PagesRes>;
} | {
    routes: import("@/routes/Routes").AppRoute[];
    isLoading: boolean;
    data: PagesRes;
    isError: false;
    error: null;
    isPending: false;
    isLoadingError: false;
    isRefetchError: false;
    isSuccess: true;
    isPlaceholderData: true;
    status: "success";
    dataUpdatedAt: number;
    errorUpdatedAt: number;
    failureCount: number;
    failureReason: Error | null;
    errorUpdateCount: number;
    isFetched: boolean;
    isFetchedAfterMount: boolean;
    isFetching: boolean;
    isInitialLoading: boolean;
    isPaused: boolean;
    isRefetching: boolean;
    isStale: boolean;
    isEnabled: boolean;
    refetch: (options?: import("@tanstack/query-core").RefetchOptions) => Promise<import("@tanstack/query-core").QueryObserverResult<PagesRes, Error>>;
    fetchStatus: import("@tanstack/query-core").FetchStatus;
    promise: Promise<PagesRes>;
};
export {};
