import type { GridColumnDef } from "@/components/ap-wijmo/grid/GridTypes";
import {
  createGroupNode,
  createLeafNode,
  type HeaderNode,
} from "@/components/ap-wijmo/grid/HeaderTree";
import type { Qsear30PrdTraceDtlRow } from "../types/Qsear30PrdTraceDtlTypes";

export const createGrdHal12ColumnDefinition = (): GridColumnDef<Qsear30PrdTraceDtlRow>[] => {
  return [
    {
      header: '',
      width: 30,
      binding: 'chk',
      dataType: 'String',
    },
    {
      header: '자재구분',
      width: 60,
      binding: 'testCi',
      dataType: 'String',
    },
    {
      header: '검사로트',
      width: 90,
      binding: 'testLot',
      dataType: 'String',
    },
    {
      header: '로트생성일',
      width: 80,
      binding: 'lotCreateDate',
      dataType: 'String',
    },
    {
      header: '오더번호',
      width: 70,
      binding: 'orderNo',
      dataType: 'String',
    },
    {
      header: '오더 순번',
      width: 40,
      binding: 'orderSeq',
      dataType: 'String',
    },
    {
      header: '제조번호',
      width: 100,
      binding: 'batchNo',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '완제품LOT',
      width: 101,
      binding: 'prdLotNo',
      dataType: 'String',
    },
    {
      header: '자재코드',
      width: 80,
      binding: 'matrCode',
      dataType: 'String',
    },
    {
      header: '자재명',
      width: 300,
      binding: 'matrName',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '판정',
      width: 80,
      binding: 'judgCode',
      dataType: 'String',
    },
    {
      header: '생산량 (EA)',
      width: 60,
      binding: 'strgQty',
      dataType: 'String',
      align: 'right',
    },
    {
      header: '포장수량 (EA)',
      width: 60,
      binding: 'pacPdtqty',
      dataType: 'String',
      align: 'right',
    },
    {
      header: '포장량 (g)',
      width: 60,
      binding: 'pacQty',
      dataType: 'String',
      align: 'right',
    },
    {
      header: '내용물 출고량(g)',
      width: 60,
      binding: 'hal3Pacqty',
      dataType: 'String',
      align: 'right',
    },
    {
      header: '확인자 Comment',
      width: 120,
      binding: 'checkUserCmnt',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '포장일자',
      width: 80,
      binding: 'pacDate',
      dataType: 'String',
    },
    {
      header: '작업시간',
      width: 60,
      binding: 'startTime',
      dataType: 'String',
    },
    {
      header: '종료',
      width: 60,
      binding: 'endTime',
      dataType: 'String',
    },
    {
      header: '설비코드',
      width: 80,
      binding: 'wrkCenter',
      dataType: 'String',
    },
    {
      header: '포장설비',
      width: 150,
      binding: 'wrkCenterName',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '작업자',
      width: 60,
      binding: 'wrkMan',
      dataType: 'String',
    },
    {
      header: '포장 순번',
      width: 38,
      binding: 'pacSeq',
      dataType: 'String',
    },
    {
      header: '특이사항',
      width: 80,
      binding: 'remark',
      dataType: 'String',
    },
    {
      header: '제조업체',
      width: 80,
      binding: 'smlPresCode',
      dataType: 'String',
    },
    {
      header: '미생물 시험번호',
      width: 110,
      binding: 'microTestLot',
      dataType: 'String',
    },
    {
      header: '미생물 검사결과',
      width: 40,
      binding: 'btraTestResult1',
      dataType: 'String',
    },
    {
      header: '2일차',
      width: 40,
      binding: 'btraTestResult2',
      dataType: 'String',
    },
    {
      header: '2일+',
      width: 40,
      binding: 'btraTestResult3',
      dataType: 'String',
    },
    {
      header: '최종',
      width: 40,
      binding: 'finalTestResult',
      dataType: 'String',
    },
    {
      header: '판정',
      width: 40,
      binding: 'finalTestJudg',
      dataType: 'String',
    },
  ];
}

export const createGrdRoh6ColumnDefinition = (): GridColumnDef<Qsear30PrdTraceDtlRow>[] => {
  return [
    {
      header: '',
      width: 30,
      binding: 'chk',
      dataType: 'String',
    },
    {
      header: '자재구분',
      width: 60,
      binding: 'testCi',
      dataType: 'String',
    },
    {
      header: '검사로트',
      width: 90,
      binding: 'testLot',
      dataType: 'String',
    },
    {
      header: '로트생성일',
      width: 80,
      binding: 'lotCreateDate',
      dataType: 'String',
    },
    {
      header: '자재코드',
      width: 60,
      binding: 'matrCode',
      dataType: 'String',
    },
    {
      header: '자재명',
      width: 250,
      binding: 'matrName',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '판정',
      width: 80,
      binding: 'judgCode',
      dataType: 'String',
    },
    {
      header: '입고량',
      width: 70,
      binding: 'strgQty',
      dataType: 'String',
    },
    {
      header: '내용물 투입량(g)',
      width: 70,
      binding: 'hal3Qty',
      dataType: 'String',
    },
    {
      header: '구입처',
      width: 120,
      binding: 'suppCmpyName',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '로트번호',
      width: 90,
      binding: 'partitionNo',
      dataType: 'String',
    },
    {
      header: '이력번호',
      width: 90,
      binding: 'partitionHystNo',
      dataType: 'String',
    },
    {
      header: '원료 구분',
      width: 70,
      binding: 'retestYn',
      dataType: 'String',
    },
    {
      header: '유통 기한',
      width: 50,
      binding: 'retestPeriod',
      dataType: 'String',
    },
    {
      header: '확인자 Comment',
      width: 80,
      binding: 'checkUserCmnt',
      dataType: 'String',
    },
    {
      header: '미생물 시험번호',
      width: 110,
      binding: 'microTestLot',
      dataType: 'String',
    },
    {
      header: '미생물 검사결과',
      width: 40,
      binding: 'btraTestResult1',
      dataType: 'String',
    },
    {
      header: '2일차',
      width: 40,
      binding: 'btraTestResult2',
      dataType: 'String',
    },
    {
      header: '2일+',
      width: 40,
      binding: 'btraTestResult3',
      dataType: 'String',
    },
    {
      header: '최종',
      width: 40,
      binding: 'finalTestResult',
      dataType: 'String',
    },
    {
      header: '판정',
      width: 40,
      binding: 'finalTestJudg',
      dataType: 'String',
    },
  ];
}

export const createGrdHal3ColumnDefinition = (): GridColumnDef<Qsear30PrdTraceDtlRow>[] => {
  return [
    {
      header: '',
      width: 30,
      binding: 'chk',
      dataType: 'String',
    },
    {
      header: '자재구분',
      width: 60,
      binding: 'testCi',
      dataType: 'String',
    },
    {
      header: '검사로트',
      width: 90,
      binding: 'testLot',
      dataType: 'String',
    },
    {
      header: '로트생성일',
      width: 80,
      binding: 'lotCreateDate',
      dataType: 'String',
    },
    {
      header: '오더번호',
      width: 60,
      binding: 'orderNo',
      dataType: 'String',
    },
    {
      header: '배치번호',
      width: 60,
      binding: 'batchNo',
      dataType: 'String',
    },
    {
      header: '자재코드',
      width: 80,
      binding: 'matrCode',
      dataType: 'String',
    },
    {
      header: '자재명',
      width: 250,
      binding: 'matrName',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '판정',
      width: 60,
      binding: 'judgCode',
      dataType: 'String',
    },
    {
      header: '제조량(g)',
      width: 70,
      binding: 'strgQty',
      dataType: 'String',
      align: 'right',
    },
    {
      header: '포장 출고량(g)',
      width: 70,
      binding: 'pacQty',
      dataType: 'String',
      align: 'right',
    },
    {
      header: '원료 투입량(g)',
      width: 70,
      binding: 'roh6Qty',
      dataType: 'String',
      align: 'right',
    },
    {
      header: '작업자',
      width: 60,
      binding: 'mnuUser',
      dataType: 'String',
    },
    {
      header: '제조장',
      width: 95,
      binding: 'mnuWrkcenter',
      dataType: 'String',
    },
    {
      header: '확인자 Comment',
      width: 80,
      binding: 'checkUserCmnt',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '제조일자',
      width: 80,
      binding: 'strgDate',
      dataType: 'String',
    },
    {
      header: '작업시간',
      width: 60,
      binding: 'startTime',
      dataType: 'String',
    },
    {
      header: '종료',
      width: 60,
      binding: 'endTime',
      dataType: 'String',
    },
    {
      header: '제조설비',
      width: 60,
      binding: 'wrkEqup01',
      dataType: 'String',
    },
    {
      header: '냉각기',
      width: 60,
      binding: 'wrkEqup03',
      dataType: 'String',
    },
    {
      header: '제조 순번',
      width: 40,
      binding: 'mnuOrderby',
      dataType: 'String',
    },
    {
      header: '미생물 시험번호',
      width: 110,
      binding: 'microTestLot',
      dataType: 'String',
    },
    {
      header: '미생물 검사결과',
      width: 40,
      binding: 'btraTestResult1',
      dataType: 'String',
    },
    {
      header: '2일차',
      width: 40,
      binding: 'btraTestResult2',
      dataType: 'String',
    },
    {
      header: '2일+',
      width: 40,
      binding: 'btraTestResult3',
      dataType: 'String',
    },
    {
      header: '최종',
      width: 40,
      binding: 'finalTestResult',
      dataType: 'String',
    },
    {
      header: '판정',
      width: 40,
      binding: 'finalTestJudg',
      dataType: 'String',
    },
  ];
}

export const createGrdFer1ColumnDefinition = (): GridColumnDef<Qsear30PrdTraceDtlRow>[] => {
  return [
    {
      header: '',
      width: 30,
      binding: 'chk',
      dataType: 'String',
    },
    {
      header: '자재구분',
      width: 60,
      binding: 'testCi',
      dataType: 'String',
    },
    {
      header: '내용물 검사로트',
      width: '*',
      binding: 'hal3TestLot',
      dataType: 'String',
    },
    {
      header: '검사로트',
      width: 90,
      binding: 'testLot',
      dataType: 'String',
    },
    {
      header: '로트생성일',
      width: 80,
      binding: 'lotCreateDate',
      dataType: 'String',
    },
    {
      header: '오더번호',
      width: 70,
      binding: 'orderNo',
      dataType: 'String',
    },
    {
      header: '오더 순번',
      width: 40,
      binding: 'orderSeq',
      dataType: 'String',
    },
    {
      header: '제조번호',
      width: 100,
      binding: 'batchNo',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '완제품LOT',
      width: 101,
      binding: 'prdLotNo',
      dataType: 'String',
    },
    {
      header: '자재코드',
      width: 80,
      binding: 'matrCode',
      dataType: 'String',
    },
    {
      header: '자재명',
      width: 300,
      binding: 'matrName',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '판정',
      width: 80,
      binding: 'judgCode',
      dataType: 'String',
    },
    {
      header: '생산량 (EA)',
      width: 60,
      binding: 'strgQty',
      dataType: 'String',
      align: 'right',
    },
    {
      header: '포장수량 (EA)',
      width: 60,
      binding: 'pacPdtqty',
      dataType: 'String',
      align: 'right',
    },
    {
      header: '포장량 (g)',
      width: 60,
      binding: 'pacQty',
      dataType: 'String',
      align: 'right',
    },
    {
      header: '내용물 출고량(g)',
      width: 60,
      binding: 'hal3Pacqty',
      dataType: 'String',
      align: 'right',
    },
    {
      header: '확인자 Comment',
      width: 120,
      binding: 'checkUserCmnt',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '포장일자',
      width: 80,
      binding: 'pacDate',
      dataType: 'String',
    },
    {
      header: '작업시간',
      width: 60,
      binding: 'startTime',
      dataType: 'String',
    },
    {
      header: '종료',
      width: 60,
      binding: 'endTime',
      dataType: 'String',
    },
    {
      header: '설비코드',
      width: 80,
      binding: 'wrkCenter',
      dataType: 'String',
    },
    {
      header: '포장설비',
      width: 150,
      binding: 'wrkCenterName',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '작업자',
      width: 60,
      binding: 'wrkMan',
      dataType: 'String',
    },
    {
      header: '포장 순번',
      width: 38,
      binding: 'pacSeq',
      dataType: 'String',
    },
    {
      header: '특이사항',
      width: 80,
      binding: 'remark',
      dataType: 'String',
    },
    {
      header: '제조업체',
      width: 80,
      binding: 'smlPresCode',
      dataType: 'String',
    },
    {
      header: '미생물 시험번호',
      width: 110,
      binding: 'microTestLot',
      dataType: 'String',
    },
    {
      header: '미생물 검사결과',
      width: 40,
      binding: 'btraTestResult1',
      dataType: 'String',
    },
    {
      header: '2일차',
      width: 40,
      binding: 'btraTestResult2',
      dataType: 'String',
    },
    {
      header: '2일+',
      width: 40,
      binding: 'btraTestResult3',
      dataType: 'String',
    },
    {
      header: '최종',
      width: 40,
      binding: 'finalTestResult',
      dataType: 'String',
    },
    {
      header: '판정',
      width: 40,
      binding: 'finalTestJudg',
      dataType: 'String',
    },
  ];
}

export const QSEAR_30_PRD_TRACE_DTL_HEADER_TREE: HeaderNode[] = [
  createLeafNode("chk", "", "chk"),
  createLeafNode("testCi", "자재구분", "testCi"),
  createLeafNode("testLot", "검사로트", "testLot"),
  createLeafNode("lotCreateDate", "로트생성일", "lotCreateDate"),
  createLeafNode("orderNo", "오더번호", "orderNo"),
  createLeafNode("orderSeq", "오더 순번", "orderSeq"),
  createLeafNode("batchNo", "제조번호", "batchNo"),
  createLeafNode("prdLotNo", "완제품LOT", "prdLotNo"),
  createLeafNode("matrCode", "자재코드", "matrCode"),
  createLeafNode("matrName", "자재명", "matrName"),
  createLeafNode("judgCode", "판정", "judgCode"),
  createLeafNode("strgQty", "생산량 (EA)", "strgQty"),
  createLeafNode("pacPdtqty", "포장수량 (EA)", "pacPdtqty"),
  createLeafNode("pacQty", "포장량 (g)", "pacQty"),
  createLeafNode("hal3Pacqty", "내용물 출고량(g)", "hal3Pacqty"),
  createLeafNode("checkUserCmnt", "확인자 Comment", "checkUserCmnt"),
  createLeafNode("pacDate", "포장일자", "pacDate"),
  createGroupNode("startTimeGroup", "작업시간", [
    createLeafNode("startTime", "시작", "startTime"),
    createLeafNode("endTime", "종료", "endTime"),
  ]),
  createLeafNode("wrkCenter", "설비코드", "wrkCenter"),
  createLeafNode("wrkCenterName", "포장설비", "wrkCenterName"),
  createLeafNode("wrkMan", "작업자", "wrkMan"),
  createLeafNode("pacSeq", "포장 순번", "pacSeq"),
  createLeafNode("remark", "특이사항", "remark"),
  createLeafNode("smlPresCode", "제조업체", "smlPresCode"),
  createLeafNode("microTestLot", "미생물 시험번호", "microTestLot"),
  createGroupNode("btraTestResult1Group", "미생물 검사결과", [
    createLeafNode("btraTestResult1", "1일차", "btraTestResult1"),
    createLeafNode("btraTestResult2", "2일차", "btraTestResult2"),
    createLeafNode("btraTestResult3", "2일+", "btraTestResult3"),
    createLeafNode("finalTestResult", "최종", "finalTestResult"),
    createLeafNode("finalTestJudg", "판정", "finalTestJudg"),
  ]),
];
