export * from '@/components/ui/accordion';
export * from '@/components/ui/alert-dialog';
export * from '@/components/ui/button';
export * from '@/components/ui/card';
export * from '@/components/ui/field';
export * from '@/components/ui/form';
export * from '@/components/ui/input';
export * from '@/components/ui/item';
export * from '@/components/ui/label';
export * from '@/components/ui/radio-group';
export * from '@/components/ui/select';
export * from '@/components/ui/separator';
export * from '@/components/ui/sonner';
export * from '@/components/ui/tabs';
export * from '@/hooks/useAppRoutes';
export * from '@/hooks/useAuthBootstrap';
export * from '@/hooks/usePageCrudAuthCheck';
export * from '@/hooks/usePageList';
export declare const getRuntimeConfig: () => {
    enableLocalRoutes: boolean;
};
