import type { GridColumnDef } from "@/components/ap-wijmo/grid/GridTypes";
import {
  createGroupNode,
  createLeafNode,
  type HeaderNode,
} from "@/components/ap-wijmo/grid/HeaderTree";
import type { Qsear35ContColorChartNRow } from "../types/Qsear35ContColorChartNTypes";

export const createGrdMainMatrColumnDefinition = (): GridColumnDef<Qsear35ContColorChartNRow>[] => {
  return [
    {
      header: '내용물코드',
      width: 70,
      binding: 'matrCode',
      dataType: 'String',
    },
    {
      header: '내용물명',
      width: 314,
      binding: 'matrName',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '로트 건수',
      width: 40,
      binding: 'batchCnt',
      dataType: 'String',
    },
    {
      header: '삭제',
      width: 40,
      binding: 'btnCancel',
      dataType: 'String',
    },
  ];
}

export const createGrid02ColumnDefinition = (): GridColumnDef<Qsear35ContColorChartNRow>[] => {
  return [
    {
      header: 'STAR_CI',
      width: '*',
      binding: 'starCi',
      dataType: 'String',
    },
    {
      header: 'COLOR_CI',
      width: '*',
      binding: 'colorCi',
      dataType: 'String',
    },
    {
      header: 'XMIN',
      width: '*',
      binding: 'xmin',
      dataType: 'String',
    },
    {
      header: 'XMAX',
      width: '*',
      binding: 'xmax',
      dataType: 'String',
    },
    {
      header: 'YMIN',
      width: '*',
      binding: 'ymin',
      dataType: 'String',
    },
    {
      header: 'YMAX',
      width: '*',
      binding: 'ymax',
      dataType: 'String',
    },
  ];
}

export const createGrid03ColumnDefinition = (): GridColumnDef<Qsear35ContColorChartNRow>[] => {
  return [
    {
      header: 'STAR_CI',
      width: '*',
      binding: 'starCi',
      dataType: 'String',
    },
    {
      header: 'COLOR_CI',
      width: '*',
      binding: 'colorCi',
      dataType: 'String',
    },
    {
      header: 'RANKNUM',
      width: '*',
      binding: 'ranknum',
      dataType: 'String',
    },
    {
      header: 'PX1',
      width: '*',
      binding: 'px1',
      dataType: 'String',
    },
    {
      header: 'PX2',
      width: '*',
      binding: 'px2',
      dataType: 'String',
    },
    {
      header: 'PX3',
      width: '*',
      binding: 'px3',
      dataType: 'String',
    },
    {
      header: 'PX4',
      width: '*',
      binding: 'px4',
      dataType: 'String',
    },
    {
      header: 'PX5',
      width: '*',
      binding: 'px5',
      dataType: 'String',
    },
    {
      header: 'PX6',
      width: '*',
      binding: 'px6',
      dataType: 'String',
    },
    {
      header: 'PX7',
      width: '*',
      binding: 'px7',
      dataType: 'String',
    },
    {
      header: 'PX8',
      width: '*',
      binding: 'px8',
      dataType: 'String',
    },
    {
      header: 'PX9',
      width: '*',
      binding: 'px9',
      dataType: 'String',
    },
    {
      header: 'PX10',
      width: '*',
      binding: 'px10',
      dataType: 'String',
    },
    {
      header: 'PX11',
      width: '*',
      binding: 'px11',
      dataType: 'String',
    },
    {
      header: 'PX12',
      width: '*',
      binding: 'px12',
      dataType: 'String',
    },
    {
      header: 'PX13',
      width: '*',
      binding: 'px13',
      dataType: 'String',
    },
    {
      header: 'PX14',
      width: '*',
      binding: 'px14',
      dataType: 'String',
    },
    {
      header: 'PX15',
      width: '*',
      binding: 'px15',
      dataType: 'String',
    },
    {
      header: 'PX16',
      width: '*',
      binding: 'px16',
      dataType: 'String',
    },
    {
      header: 'PX17',
      width: '*',
      binding: 'px17',
      dataType: 'String',
    },
    {
      header: 'PX18',
      width: '*',
      binding: 'px18',
      dataType: 'String',
    },
    {
      header: 'PX19',
      width: '*',
      binding: 'px19',
      dataType: 'String',
    },
    {
      header: 'PX20',
      width: '*',
      binding: 'px20',
      dataType: 'String',
    },
    {
      header: 'PX21',
      width: '*',
      binding: 'px21',
      dataType: 'String',
    },
    {
      header: 'PX22',
      width: '*',
      binding: 'px22',
      dataType: 'String',
    },
    {
      header: 'PX23',
      width: '*',
      binding: 'px23',
      dataType: 'String',
    },
    {
      header: 'PX24',
      width: '*',
      binding: 'px24',
      dataType: 'String',
    },
    {
      header: 'PX25',
      width: '*',
      binding: 'px25',
      dataType: 'String',
    },
    {
      header: 'PX26',
      width: '*',
      binding: 'px26',
      dataType: 'String',
    },
    {
      header: 'PX27',
      width: '*',
      binding: 'px27',
      dataType: 'String',
    },
    {
      header: 'PX28',
      width: '*',
      binding: 'px28',
      dataType: 'String',
    },
    {
      header: 'PX29',
      width: '*',
      binding: 'px29',
      dataType: 'String',
    },
    {
      header: 'PX30',
      width: '*',
      binding: 'px30',
      dataType: 'String',
    },
    {
      header: 'PX31',
      width: '*',
      binding: 'px31',
      dataType: 'String',
    },
    {
      header: 'PX32',
      width: '*',
      binding: 'px32',
      dataType: 'String',
    },
    {
      header: 'PX33',
      width: '*',
      binding: 'px33',
      dataType: 'String',
    },
    {
      header: 'PX34',
      width: '*',
      binding: 'px34',
      dataType: 'String',
    },
    {
      header: 'PX35',
      width: '*',
      binding: 'px35',
      dataType: 'String',
    },
    {
      header: 'PX36',
      width: '*',
      binding: 'px36',
      dataType: 'String',
    },
    {
      header: 'PX37',
      width: '*',
      binding: 'px37',
      dataType: 'String',
    },
    {
      header: 'PX38',
      width: '*',
      binding: 'px38',
      dataType: 'String',
    },
    {
      header: 'PX39',
      width: '*',
      binding: 'px39',
      dataType: 'String',
    },
    {
      header: 'PX40',
      width: '*',
      binding: 'px40',
      dataType: 'String',
    },
    {
      header: 'PX41',
      width: '*',
      binding: 'px41',
      dataType: 'String',
    },
    {
      header: 'PX42',
      width: '*',
      binding: 'px42',
      dataType: 'String',
    },
    {
      header: 'PX43',
      width: '*',
      binding: 'px43',
      dataType: 'String',
    },
    {
      header: 'PX44',
      width: '*',
      binding: 'px44',
      dataType: 'String',
    },
    {
      header: 'PX45',
      width: '*',
      binding: 'px45',
      dataType: 'String',
    },
    {
      header: 'PX46',
      width: '*',
      binding: 'px46',
      dataType: 'String',
    },
    {
      header: 'PX47',
      width: '*',
      binding: 'px47',
      dataType: 'String',
    },
    {
      header: 'PX48',
      width: '*',
      binding: 'px48',
      dataType: 'String',
    },
    {
      header: 'PX49',
      width: '*',
      binding: 'px49',
      dataType: 'String',
    },
    {
      header: 'PX50',
      width: '*',
      binding: 'px50',
      dataType: 'String',
    },
    {
      header: 'PX51',
      width: '*',
      binding: 'px51',
      dataType: 'String',
    },
    {
      header: 'PX52',
      width: '*',
      binding: 'px52',
      dataType: 'String',
    },
    {
      header: 'PX53',
      width: '*',
      binding: 'px53',
      dataType: 'String',
    },
    {
      header: 'PX54',
      width: '*',
      binding: 'px54',
      dataType: 'String',
    },
    {
      header: 'PX55',
      width: '*',
      binding: 'px55',
      dataType: 'String',
    },
    {
      header: 'PX56',
      width: '*',
      binding: 'px56',
      dataType: 'String',
    },
    {
      header: 'PX57',
      width: '*',
      binding: 'px57',
      dataType: 'String',
    },
    {
      header: 'PX58',
      width: '*',
      binding: 'px58',
      dataType: 'String',
    },
    {
      header: 'PX59',
      width: '*',
      binding: 'px59',
      dataType: 'String',
    },
    {
      header: 'PX60',
      width: '*',
      binding: 'px60',
      dataType: 'String',
    },
    {
      header: 'PX61',
      width: '*',
      binding: 'px61',
      dataType: 'String',
    },
    {
      header: 'PX62',
      width: '*',
      binding: 'px62',
      dataType: 'String',
    },
    {
      header: 'PX63',
      width: '*',
      binding: 'px63',
      dataType: 'String',
    },
    {
      header: 'PX64',
      width: '*',
      binding: 'px64',
      dataType: 'String',
    },
    {
      header: 'PX65',
      width: '*',
      binding: 'px65',
      dataType: 'String',
    },
    {
      header: 'PX66',
      width: '*',
      binding: 'px66',
      dataType: 'String',
    },
    {
      header: 'PX67',
      width: '*',
      binding: 'px67',
      dataType: 'String',
    },
    {
      header: 'PX68',
      width: '*',
      binding: 'px68',
      dataType: 'String',
    },
    {
      header: 'PX69',
      width: '*',
      binding: 'px69',
      dataType: 'String',
    },
    {
      header: 'PX70',
      width: '*',
      binding: 'px70',
      dataType: 'String',
    },
    {
      header: 'PX71',
      width: '*',
      binding: 'px71',
      dataType: 'String',
    },
    {
      header: 'PX72',
      width: '*',
      binding: 'px72',
      dataType: 'String',
    },
    {
      header: 'PX73',
      width: '*',
      binding: 'px73',
      dataType: 'String',
    },
    {
      header: 'PX74',
      width: '*',
      binding: 'px74',
      dataType: 'String',
    },
    {
      header: 'PX75',
      width: '*',
      binding: 'px75',
      dataType: 'String',
    },
    {
      header: 'PX76',
      width: '*',
      binding: 'px76',
      dataType: 'String',
    },
    {
      header: 'PX77',
      width: '*',
      binding: 'px77',
      dataType: 'String',
    },
    {
      header: 'PX78',
      width: '*',
      binding: 'px78',
      dataType: 'String',
    },
    {
      header: 'PX79',
      width: '*',
      binding: 'px79',
      dataType: 'String',
    },
    {
      header: 'PX80',
      width: '*',
      binding: 'px80',
      dataType: 'String',
    },
    {
      header: 'PX81',
      width: '*',
      binding: 'px81',
      dataType: 'String',
    },
    {
      header: 'PX82',
      width: '*',
      binding: 'px82',
      dataType: 'String',
    },
    {
      header: 'PX83',
      width: '*',
      binding: 'px83',
      dataType: 'String',
    },
    {
      header: 'PX84',
      width: '*',
      binding: 'px84',
      dataType: 'String',
    },
    {
      header: 'PX85',
      width: '*',
      binding: 'px85',
      dataType: 'String',
    },
    {
      header: 'PX86',
      width: '*',
      binding: 'px86',
      dataType: 'String',
    },
    {
      header: 'PX87',
      width: '*',
      binding: 'px87',
      dataType: 'String',
    },
    {
      header: 'PX88',
      width: '*',
      binding: 'px88',
      dataType: 'String',
    },
    {
      header: 'PX89',
      width: '*',
      binding: 'px89',
      dataType: 'String',
    },
    {
      header: 'PX90',
      width: '*',
      binding: 'px90',
      dataType: 'String',
    },
    {
      header: 'PX91',
      width: '*',
      binding: 'px91',
      dataType: 'String',
    },
    {
      header: 'PX92',
      width: '*',
      binding: 'px92',
      dataType: 'String',
    },
    {
      header: 'PX93',
      width: '*',
      binding: 'px93',
      dataType: 'String',
    },
    {
      header: 'PX94',
      width: '*',
      binding: 'px94',
      dataType: 'String',
    },
    {
      header: 'PX95',
      width: '*',
      binding: 'px95',
      dataType: 'String',
    },
    {
      header: 'PX96',
      width: '*',
      binding: 'px96',
      dataType: 'String',
    },
    {
      header: 'PX97',
      width: '*',
      binding: 'px97',
      dataType: 'String',
    },
    {
      header: 'PX98',
      width: '*',
      binding: 'px98',
      dataType: 'String',
    },
    {
      header: 'PX99',
      width: '*',
      binding: 'px99',
      dataType: 'String',
    },
    {
      header: 'PX100',
      width: '*',
      binding: 'px100',
      dataType: 'String',
    },
    {
      header: 'PY1',
      width: '*',
      binding: 'py1',
      dataType: 'String',
    },
    {
      header: 'PY2',
      width: '*',
      binding: 'py2',
      dataType: 'String',
    },
    {
      header: 'PY3',
      width: '*',
      binding: 'py3',
      dataType: 'String',
    },
    {
      header: 'PY4',
      width: '*',
      binding: 'py4',
      dataType: 'String',
    },
    {
      header: 'PY5',
      width: '*',
      binding: 'py5',
      dataType: 'String',
    },
    {
      header: 'PY6',
      width: '*',
      binding: 'py6',
      dataType: 'String',
    },
    {
      header: 'PY7',
      width: '*',
      binding: 'py7',
      dataType: 'String',
    },
    {
      header: 'PY8',
      width: '*',
      binding: 'py8',
      dataType: 'String',
    },
    {
      header: 'PY9',
      width: '*',
      binding: 'py9',
      dataType: 'String',
    },
    {
      header: 'PY10',
      width: '*',
      binding: 'py10',
      dataType: 'String',
    },
    {
      header: 'PY11',
      width: '*',
      binding: 'py11',
      dataType: 'String',
    },
    {
      header: 'PY12',
      width: '*',
      binding: 'py12',
      dataType: 'String',
    },
    {
      header: 'PY13',
      width: '*',
      binding: 'py13',
      dataType: 'String',
    },
    {
      header: 'PY14',
      width: '*',
      binding: 'py14',
      dataType: 'String',
    },
    {
      header: 'PY15',
      width: '*',
      binding: 'py15',
      dataType: 'String',
    },
    {
      header: 'PY16',
      width: '*',
      binding: 'py16',
      dataType: 'String',
    },
    {
      header: 'PY17',
      width: '*',
      binding: 'py17',
      dataType: 'String',
    },
    {
      header: 'PY18',
      width: '*',
      binding: 'py18',
      dataType: 'String',
    },
    {
      header: 'PY19',
      width: '*',
      binding: 'py19',
      dataType: 'String',
    },
    {
      header: 'PY20',
      width: '*',
      binding: 'py20',
      dataType: 'String',
    },
    {
      header: 'PY21',
      width: '*',
      binding: 'py21',
      dataType: 'String',
    },
    {
      header: 'PY22',
      width: '*',
      binding: 'py22',
      dataType: 'String',
    },
    {
      header: 'PY23',
      width: '*',
      binding: 'py23',
      dataType: 'String',
    },
    {
      header: 'PY24',
      width: '*',
      binding: 'py24',
      dataType: 'String',
    },
    {
      header: 'PY25',
      width: '*',
      binding: 'py25',
      dataType: 'String',
    },
    {
      header: 'PY26',
      width: '*',
      binding: 'py26',
      dataType: 'String',
    },
    {
      header: 'PY27',
      width: '*',
      binding: 'py27',
      dataType: 'String',
    },
    {
      header: 'PY28',
      width: '*',
      binding: 'py28',
      dataType: 'String',
    },
    {
      header: 'PY29',
      width: '*',
      binding: 'py29',
      dataType: 'String',
    },
    {
      header: 'PY30',
      width: '*',
      binding: 'py30',
      dataType: 'String',
    },
    {
      header: 'PY31',
      width: '*',
      binding: 'py31',
      dataType: 'String',
    },
    {
      header: 'PY32',
      width: '*',
      binding: 'py32',
      dataType: 'String',
    },
    {
      header: 'PY33',
      width: '*',
      binding: 'py33',
      dataType: 'String',
    },
    {
      header: 'PY34',
      width: '*',
      binding: 'py34',
      dataType: 'String',
    },
    {
      header: 'PY35',
      width: '*',
      binding: 'py35',
      dataType: 'String',
    },
    {
      header: 'PY36',
      width: '*',
      binding: 'py36',
      dataType: 'String',
    },
    {
      header: 'PY37',
      width: '*',
      binding: 'py37',
      dataType: 'String',
    },
    {
      header: 'PY38',
      width: '*',
      binding: 'py38',
      dataType: 'String',
    },
    {
      header: 'PY39',
      width: '*',
      binding: 'py39',
      dataType: 'String',
    },
    {
      header: 'PY40',
      width: '*',
      binding: 'py40',
      dataType: 'String',
    },
    {
      header: 'PY41',
      width: '*',
      binding: 'py41',
      dataType: 'String',
    },
    {
      header: 'PY42',
      width: '*',
      binding: 'py42',
      dataType: 'String',
    },
    {
      header: 'PY43',
      width: '*',
      binding: 'py43',
      dataType: 'String',
    },
    {
      header: 'PY44',
      width: '*',
      binding: 'py44',
      dataType: 'String',
    },
    {
      header: 'PY45',
      width: '*',
      binding: 'py45',
      dataType: 'String',
    },
    {
      header: 'PY46',
      width: '*',
      binding: 'py46',
      dataType: 'String',
    },
    {
      header: 'PY47',
      width: '*',
      binding: 'py47',
      dataType: 'String',
    },
    {
      header: 'PY48',
      width: '*',
      binding: 'py48',
      dataType: 'String',
    },
    {
      header: 'PY49',
      width: '*',
      binding: 'py49',
      dataType: 'String',
    },
    {
      header: 'PY50',
      width: '*',
      binding: 'py50',
      dataType: 'String',
    },
    {
      header: 'PY51',
      width: '*',
      binding: 'py51',
      dataType: 'String',
    },
    {
      header: 'PY52',
      width: '*',
      binding: 'py52',
      dataType: 'String',
    },
    {
      header: 'PY53',
      width: '*',
      binding: 'py53',
      dataType: 'String',
    },
    {
      header: 'PY54',
      width: '*',
      binding: 'py54',
      dataType: 'String',
    },
    {
      header: 'PY55',
      width: '*',
      binding: 'py55',
      dataType: 'String',
    },
    {
      header: 'PY56',
      width: '*',
      binding: 'py56',
      dataType: 'String',
    },
    {
      header: 'PY57',
      width: '*',
      binding: 'py57',
      dataType: 'String',
    },
    {
      header: 'PY58',
      width: '*',
      binding: 'py58',
      dataType: 'String',
    },
    {
      header: 'PY59',
      width: '*',
      binding: 'py59',
      dataType: 'String',
    },
    {
      header: 'PY60',
      width: '*',
      binding: 'py60',
      dataType: 'String',
    },
    {
      header: 'PY61',
      width: '*',
      binding: 'py61',
      dataType: 'String',
    },
    {
      header: 'PY62',
      width: '*',
      binding: 'py62',
      dataType: 'String',
    },
    {
      header: 'PY63',
      width: '*',
      binding: 'py63',
      dataType: 'String',
    },
    {
      header: 'PY64',
      width: '*',
      binding: 'py64',
      dataType: 'String',
    },
    {
      header: 'PY65',
      width: '*',
      binding: 'py65',
      dataType: 'String',
    },
    {
      header: 'PY66',
      width: '*',
      binding: 'py66',
      dataType: 'String',
    },
    {
      header: 'PY67',
      width: '*',
      binding: 'py67',
      dataType: 'String',
    },
    {
      header: 'PY68',
      width: '*',
      binding: 'py68',
      dataType: 'String',
    },
    {
      header: 'PY69',
      width: '*',
      binding: 'py69',
      dataType: 'String',
    },
    {
      header: 'PY70',
      width: '*',
      binding: 'py70',
      dataType: 'String',
    },
    {
      header: 'PY71',
      width: '*',
      binding: 'py71',
      dataType: 'String',
    },
    {
      header: 'PY72',
      width: '*',
      binding: 'py72',
      dataType: 'String',
    },
    {
      header: 'PY73',
      width: '*',
      binding: 'py73',
      dataType: 'String',
    },
    {
      header: 'PY74',
      width: '*',
      binding: 'py74',
      dataType: 'String',
    },
    {
      header: 'PY75',
      width: '*',
      binding: 'py75',
      dataType: 'String',
    },
    {
      header: 'PY76',
      width: '*',
      binding: 'py76',
      dataType: 'String',
    },
    {
      header: 'PY77',
      width: '*',
      binding: 'py77',
      dataType: 'String',
    },
    {
      header: 'PY78',
      width: '*',
      binding: 'py78',
      dataType: 'String',
    },
    {
      header: 'PY79',
      width: '*',
      binding: 'py79',
      dataType: 'String',
    },
    {
      header: 'PY80',
      width: '*',
      binding: 'py80',
      dataType: 'String',
    },
    {
      header: 'PY81',
      width: '*',
      binding: 'py81',
      dataType: 'String',
    },
    {
      header: 'PY82',
      width: '*',
      binding: 'py82',
      dataType: 'String',
    },
    {
      header: 'PY83',
      width: '*',
      binding: 'py83',
      dataType: 'String',
    },
    {
      header: 'PY84',
      width: '*',
      binding: 'py84',
      dataType: 'String',
    },
    {
      header: 'PY85',
      width: '*',
      binding: 'py85',
      dataType: 'String',
    },
    {
      header: 'PY86',
      width: '*',
      binding: 'py86',
      dataType: 'String',
    },
    {
      header: 'PY87',
      width: '*',
      binding: 'py87',
      dataType: 'String',
    },
    {
      header: 'PY88',
      width: '*',
      binding: 'py88',
      dataType: 'String',
    },
    {
      header: 'PY89',
      width: '*',
      binding: 'py89',
      dataType: 'String',
    },
    {
      header: 'PY90',
      width: '*',
      binding: 'py90',
      dataType: 'String',
    },
    {
      header: 'PY91',
      width: '*',
      binding: 'py91',
      dataType: 'String',
    },
    {
      header: 'PY92',
      width: '*',
      binding: 'py92',
      dataType: 'String',
    },
    {
      header: 'PY93',
      width: '*',
      binding: 'py93',
      dataType: 'String',
    },
    {
      header: 'PY94',
      width: '*',
      binding: 'py94',
      dataType: 'String',
    },
    {
      header: 'PY95',
      width: '*',
      binding: 'py95',
      dataType: 'String',
    },
    {
      header: 'PY96',
      width: '*',
      binding: 'py96',
      dataType: 'String',
    },
    {
      header: 'PY97',
      width: '*',
      binding: 'py97',
      dataType: 'String',
    },
    {
      header: 'PY98',
      width: '*',
      binding: 'py98',
      dataType: 'String',
    },
    {
      header: 'PY99',
      width: '*',
      binding: 'py99',
      dataType: 'String',
    },
    {
      header: 'PY100',
      width: '*',
      binding: 'py100',
      dataType: 'String',
    },
    {
      header: 'X1',
      width: '*',
      binding: 'x1',
      dataType: 'String',
    },
    {
      header: 'X2',
      width: '*',
      binding: 'x2',
      dataType: 'String',
    },
    {
      header: 'X3',
      width: '*',
      binding: 'x3',
      dataType: 'String',
    },
    {
      header: 'X4',
      width: '*',
      binding: 'x4',
      dataType: 'String',
    },
    {
      header: 'X5',
      width: '*',
      binding: 'x5',
      dataType: 'String',
    },
    {
      header: 'X6',
      width: '*',
      binding: 'x6',
      dataType: 'String',
    },
    {
      header: 'X7',
      width: '*',
      binding: 'x7',
      dataType: 'String',
    },
    {
      header: 'X8',
      width: '*',
      binding: 'x8',
      dataType: 'String',
    },
    {
      header: 'X9',
      width: '*',
      binding: 'x9',
      dataType: 'String',
    },
    {
      header: 'X10',
      width: '*',
      binding: 'x10',
      dataType: 'String',
    },
    {
      header: 'X11',
      width: '*',
      binding: 'x11',
      dataType: 'String',
    },
    {
      header: 'X12',
      width: '*',
      binding: 'x12',
      dataType: 'String',
    },
    {
      header: 'X13',
      width: '*',
      binding: 'x13',
      dataType: 'String',
    },
    {
      header: 'X14',
      width: '*',
      binding: 'x14',
      dataType: 'String',
    },
    {
      header: 'X15',
      width: '*',
      binding: 'x15',
      dataType: 'String',
    },
    {
      header: 'X16',
      width: '*',
      binding: 'x16',
      dataType: 'String',
    },
    {
      header: 'X17',
      width: '*',
      binding: 'x17',
      dataType: 'String',
    },
    {
      header: 'X18',
      width: '*',
      binding: 'x18',
      dataType: 'String',
    },
    {
      header: 'X19',
      width: '*',
      binding: 'x19',
      dataType: 'String',
    },
    {
      header: 'X20',
      width: '*',
      binding: 'x20',
      dataType: 'String',
    },
    {
      header: 'X21',
      width: '*',
      binding: 'x21',
      dataType: 'String',
    },
    {
      header: 'X22',
      width: '*',
      binding: 'x22',
      dataType: 'String',
    },
    {
      header: 'X23',
      width: '*',
      binding: 'x23',
      dataType: 'String',
    },
    {
      header: 'X24',
      width: '*',
      binding: 'x24',
      dataType: 'String',
    },
    {
      header: 'X25',
      width: '*',
      binding: 'x25',
      dataType: 'String',
    },
    {
      header: 'X26',
      width: '*',
      binding: 'x26',
      dataType: 'String',
    },
    {
      header: 'X27',
      width: '*',
      binding: 'x27',
      dataType: 'String',
    },
    {
      header: 'X28',
      width: '*',
      binding: 'x28',
      dataType: 'String',
    },
    {
      header: 'X29',
      width: '*',
      binding: 'x29',
      dataType: 'String',
    },
    {
      header: 'X30',
      width: '*',
      binding: 'x30',
      dataType: 'String',
    },
    {
      header: 'X31',
      width: '*',
      binding: 'x31',
      dataType: 'String',
    },
    {
      header: 'X32',
      width: '*',
      binding: 'x32',
      dataType: 'String',
    },
    {
      header: 'X33',
      width: '*',
      binding: 'x33',
      dataType: 'String',
    },
    {
      header: 'X34',
      width: '*',
      binding: 'x34',
      dataType: 'String',
    },
    {
      header: 'X35',
      width: '*',
      binding: 'x35',
      dataType: 'String',
    },
    {
      header: 'X36',
      width: '*',
      binding: 'x36',
      dataType: 'String',
    },
    {
      header: 'X37',
      width: '*',
      binding: 'x37',
      dataType: 'String',
    },
    {
      header: 'X38',
      width: '*',
      binding: 'x38',
      dataType: 'String',
    },
    {
      header: 'X39',
      width: '*',
      binding: 'x39',
      dataType: 'String',
    },
    {
      header: 'X40',
      width: '*',
      binding: 'x40',
      dataType: 'String',
    },
    {
      header: 'X41',
      width: '*',
      binding: 'x41',
      dataType: 'String',
    },
    {
      header: 'X42',
      width: '*',
      binding: 'x42',
      dataType: 'String',
    },
    {
      header: 'X43',
      width: '*',
      binding: 'x43',
      dataType: 'String',
    },
    {
      header: 'X44',
      width: '*',
      binding: 'x44',
      dataType: 'String',
    },
    {
      header: 'X45',
      width: '*',
      binding: 'x45',
      dataType: 'String',
    },
    {
      header: 'X46',
      width: '*',
      binding: 'x46',
      dataType: 'String',
    },
    {
      header: 'X47',
      width: '*',
      binding: 'x47',
      dataType: 'String',
    },
    {
      header: 'X48',
      width: '*',
      binding: 'x48',
      dataType: 'String',
    },
    {
      header: 'X49',
      width: '*',
      binding: 'x49',
      dataType: 'String',
    },
    {
      header: 'X50',
      width: '*',
      binding: 'x50',
      dataType: 'String',
    },
    {
      header: 'X51',
      width: '*',
      binding: 'x51',
      dataType: 'String',
    },
    {
      header: 'X52',
      width: '*',
      binding: 'x52',
      dataType: 'String',
    },
    {
      header: 'X53',
      width: '*',
      binding: 'x53',
      dataType: 'String',
    },
    {
      header: 'X54',
      width: '*',
      binding: 'x54',
      dataType: 'String',
    },
    {
      header: 'X55',
      width: '*',
      binding: 'x55',
      dataType: 'String',
    },
    {
      header: 'X56',
      width: '*',
      binding: 'x56',
      dataType: 'String',
    },
    {
      header: 'X57',
      width: '*',
      binding: 'x57',
      dataType: 'String',
    },
    {
      header: 'X58',
      width: '*',
      binding: 'x58',
      dataType: 'String',
    },
    {
      header: 'X59',
      width: '*',
      binding: 'x59',
      dataType: 'String',
    },
    {
      header: 'X60',
      width: '*',
      binding: 'x60',
      dataType: 'String',
    },
    {
      header: 'X61',
      width: '*',
      binding: 'x61',
      dataType: 'String',
    },
    {
      header: 'X62',
      width: '*',
      binding: 'x62',
      dataType: 'String',
    },
    {
      header: 'X63',
      width: '*',
      binding: 'x63',
      dataType: 'String',
    },
    {
      header: 'X64',
      width: '*',
      binding: 'x64',
      dataType: 'String',
    },
    {
      header: 'X65',
      width: '*',
      binding: 'x65',
      dataType: 'String',
    },
    {
      header: 'X66',
      width: '*',
      binding: 'x66',
      dataType: 'String',
    },
    {
      header: 'X67',
      width: '*',
      binding: 'x67',
      dataType: 'String',
    },
    {
      header: 'X68',
      width: '*',
      binding: 'x68',
      dataType: 'String',
    },
    {
      header: 'X69',
      width: '*',
      binding: 'x69',
      dataType: 'String',
    },
    {
      header: 'X70',
      width: '*',
      binding: 'x70',
      dataType: 'String',
    },
    {
      header: 'X71',
      width: '*',
      binding: 'x71',
      dataType: 'String',
    },
    {
      header: 'X72',
      width: '*',
      binding: 'x72',
      dataType: 'String',
    },
    {
      header: 'X73',
      width: '*',
      binding: 'x73',
      dataType: 'String',
    },
    {
      header: 'X74',
      width: '*',
      binding: 'x74',
      dataType: 'String',
    },
    {
      header: 'X75',
      width: '*',
      binding: 'x75',
      dataType: 'String',
    },
    {
      header: 'X76',
      width: '*',
      binding: 'x76',
      dataType: 'String',
    },
    {
      header: 'X77',
      width: '*',
      binding: 'x77',
      dataType: 'String',
    },
    {
      header: 'X78',
      width: '*',
      binding: 'x78',
      dataType: 'String',
    },
    {
      header: 'X79',
      width: '*',
      binding: 'x79',
      dataType: 'String',
    },
    {
      header: 'X80',
      width: '*',
      binding: 'x80',
      dataType: 'String',
    },
    {
      header: 'X81',
      width: '*',
      binding: 'x81',
      dataType: 'String',
    },
    {
      header: 'X82',
      width: '*',
      binding: 'x82',
      dataType: 'String',
    },
    {
      header: 'X83',
      width: '*',
      binding: 'x83',
      dataType: 'String',
    },
    {
      header: 'X84',
      width: '*',
      binding: 'x84',
      dataType: 'String',
    },
    {
      header: 'X85',
      width: '*',
      binding: 'x85',
      dataType: 'String',
    },
    {
      header: 'X86',
      width: '*',
      binding: 'x86',
      dataType: 'String',
    },
    {
      header: 'X87',
      width: '*',
      binding: 'x87',
      dataType: 'String',
    },
    {
      header: 'X88',
      width: '*',
      binding: 'x88',
      dataType: 'String',
    },
    {
      header: 'X89',
      width: '*',
      binding: 'x89',
      dataType: 'String',
    },
    {
      header: 'X90',
      width: '*',
      binding: 'x90',
      dataType: 'String',
    },
    {
      header: 'X91',
      width: '*',
      binding: 'x91',
      dataType: 'String',
    },
    {
      header: 'X92',
      width: '*',
      binding: 'x92',
      dataType: 'String',
    },
    {
      header: 'X93',
      width: '*',
      binding: 'x93',
      dataType: 'String',
    },
    {
      header: 'X94',
      width: '*',
      binding: 'x94',
      dataType: 'String',
    },
    {
      header: 'X95',
      width: '*',
      binding: 'x95',
      dataType: 'String',
    },
    {
      header: 'X96',
      width: '*',
      binding: 'x96',
      dataType: 'String',
    },
    {
      header: 'X97',
      width: '*',
      binding: 'x97',
      dataType: 'String',
    },
    {
      header: 'X98',
      width: '*',
      binding: 'x98',
      dataType: 'String',
    },
    {
      header: 'X99',
      width: '*',
      binding: 'x99',
      dataType: 'String',
    },
    {
      header: 'X100',
      width: '*',
      binding: 'x100',
      dataType: 'String',
    },
    {
      header: 'Y1',
      width: '*',
      binding: 'y1',
      dataType: 'String',
    },
    {
      header: 'Y2',
      width: '*',
      binding: 'y2',
      dataType: 'String',
    },
    {
      header: 'Y3',
      width: '*',
      binding: 'y3',
      dataType: 'String',
    },
    {
      header: 'Y4',
      width: '*',
      binding: 'y4',
      dataType: 'String',
    },
    {
      header: 'Y5',
      width: '*',
      binding: 'y5',
      dataType: 'String',
    },
    {
      header: 'Y6',
      width: '*',
      binding: 'y6',
      dataType: 'String',
    },
    {
      header: 'Y7',
      width: '*',
      binding: 'y7',
      dataType: 'String',
    },
    {
      header: 'Y8',
      width: '*',
      binding: 'y8',
      dataType: 'String',
    },
    {
      header: 'Y9',
      width: '*',
      binding: 'y9',
      dataType: 'String',
    },
    {
      header: 'Y10',
      width: '*',
      binding: 'y10',
      dataType: 'String',
    },
    {
      header: 'Y11',
      width: '*',
      binding: 'y11',
      dataType: 'String',
    },
    {
      header: 'Y12',
      width: '*',
      binding: 'y12',
      dataType: 'String',
    },
    {
      header: 'Y13',
      width: '*',
      binding: 'y13',
      dataType: 'String',
    },
    {
      header: 'Y14',
      width: '*',
      binding: 'y14',
      dataType: 'String',
    },
    {
      header: 'Y15',
      width: '*',
      binding: 'y15',
      dataType: 'String',
    },
    {
      header: 'Y16',
      width: '*',
      binding: 'y16',
      dataType: 'String',
    },
    {
      header: 'Y17',
      width: '*',
      binding: 'y17',
      dataType: 'String',
    },
    {
      header: 'Y18',
      width: '*',
      binding: 'y18',
      dataType: 'String',
    },
    {
      header: 'Y19',
      width: '*',
      binding: 'y19',
      dataType: 'String',
    },
    {
      header: 'Y20',
      width: '*',
      binding: 'y20',
      dataType: 'String',
    },
    {
      header: 'Y21',
      width: '*',
      binding: 'y21',
      dataType: 'String',
    },
    {
      header: 'Y22',
      width: '*',
      binding: 'y22',
      dataType: 'String',
    },
    {
      header: 'Y23',
      width: '*',
      binding: 'y23',
      dataType: 'String',
    },
    {
      header: 'Y24',
      width: '*',
      binding: 'y24',
      dataType: 'String',
    },
    {
      header: 'Y25',
      width: '*',
      binding: 'y25',
      dataType: 'String',
    },
    {
      header: 'Y26',
      width: '*',
      binding: 'y26',
      dataType: 'String',
    },
    {
      header: 'Y27',
      width: '*',
      binding: 'y27',
      dataType: 'String',
    },
    {
      header: 'Y28',
      width: '*',
      binding: 'y28',
      dataType: 'String',
    },
    {
      header: 'Y29',
      width: '*',
      binding: 'y29',
      dataType: 'String',
    },
    {
      header: 'Y30',
      width: '*',
      binding: 'y30',
      dataType: 'String',
    },
    {
      header: 'Y31',
      width: '*',
      binding: 'y31',
      dataType: 'String',
    },
    {
      header: 'Y32',
      width: '*',
      binding: 'y32',
      dataType: 'String',
    },
    {
      header: 'Y33',
      width: '*',
      binding: 'y33',
      dataType: 'String',
    },
    {
      header: 'Y34',
      width: '*',
      binding: 'y34',
      dataType: 'String',
    },
    {
      header: 'Y35',
      width: '*',
      binding: 'y35',
      dataType: 'String',
    },
    {
      header: 'Y36',
      width: '*',
      binding: 'y36',
      dataType: 'String',
    },
    {
      header: 'Y37',
      width: '*',
      binding: 'y37',
      dataType: 'String',
    },
    {
      header: 'Y38',
      width: '*',
      binding: 'y38',
      dataType: 'String',
    },
    {
      header: 'Y39',
      width: '*',
      binding: 'y39',
      dataType: 'String',
    },
    {
      header: 'Y40',
      width: '*',
      binding: 'y40',
      dataType: 'String',
    },
    {
      header: 'Y41',
      width: '*',
      binding: 'y41',
      dataType: 'String',
    },
    {
      header: 'Y42',
      width: '*',
      binding: 'y42',
      dataType: 'String',
    },
    {
      header: 'Y43',
      width: '*',
      binding: 'y43',
      dataType: 'String',
    },
    {
      header: 'Y44',
      width: '*',
      binding: 'y44',
      dataType: 'String',
    },
    {
      header: 'Y45',
      width: '*',
      binding: 'y45',
      dataType: 'String',
    },
    {
      header: 'Y46',
      width: '*',
      binding: 'y46',
      dataType: 'String',
    },
    {
      header: 'Y47',
      width: '*',
      binding: 'y47',
      dataType: 'String',
    },
    {
      header: 'Y48',
      width: '*',
      binding: 'y48',
      dataType: 'String',
    },
    {
      header: 'Y49',
      width: '*',
      binding: 'y49',
      dataType: 'String',
    },
    {
      header: 'Y50',
      width: '*',
      binding: 'y50',
      dataType: 'String',
    },
    {
      header: 'Y51',
      width: '*',
      binding: 'y51',
      dataType: 'String',
    },
    {
      header: 'Y52',
      width: '*',
      binding: 'y52',
      dataType: 'String',
    },
    {
      header: 'Y53',
      width: '*',
      binding: 'y53',
      dataType: 'String',
    },
    {
      header: 'Y54',
      width: '*',
      binding: 'y54',
      dataType: 'String',
    },
    {
      header: 'Y55',
      width: '*',
      binding: 'y55',
      dataType: 'String',
    },
    {
      header: 'Y56',
      width: '*',
      binding: 'y56',
      dataType: 'String',
    },
    {
      header: 'Y57',
      width: '*',
      binding: 'y57',
      dataType: 'String',
    },
    {
      header: 'Y58',
      width: '*',
      binding: 'y58',
      dataType: 'String',
    },
    {
      header: 'Y59',
      width: '*',
      binding: 'y59',
      dataType: 'String',
    },
    {
      header: 'Y60',
      width: '*',
      binding: 'y60',
      dataType: 'String',
    },
    {
      header: 'Y61',
      width: '*',
      binding: 'y61',
      dataType: 'String',
    },
    {
      header: 'Y62',
      width: '*',
      binding: 'y62',
      dataType: 'String',
    },
    {
      header: 'Y63',
      width: '*',
      binding: 'y63',
      dataType: 'String',
    },
    {
      header: 'Y64',
      width: '*',
      binding: 'y64',
      dataType: 'String',
    },
    {
      header: 'Y65',
      width: '*',
      binding: 'y65',
      dataType: 'String',
    },
    {
      header: 'Y66',
      width: '*',
      binding: 'y66',
      dataType: 'String',
    },
    {
      header: 'Y67',
      width: '*',
      binding: 'y67',
      dataType: 'String',
    },
    {
      header: 'Y68',
      width: '*',
      binding: 'y68',
      dataType: 'String',
    },
    {
      header: 'Y69',
      width: '*',
      binding: 'y69',
      dataType: 'String',
    },
    {
      header: 'Y70',
      width: '*',
      binding: 'y70',
      dataType: 'String',
    },
    {
      header: 'Y71',
      width: '*',
      binding: 'y71',
      dataType: 'String',
    },
    {
      header: 'Y72',
      width: '*',
      binding: 'y72',
      dataType: 'String',
    },
    {
      header: 'Y73',
      width: '*',
      binding: 'y73',
      dataType: 'String',
    },
    {
      header: 'Y74',
      width: '*',
      binding: 'y74',
      dataType: 'String',
    },
    {
      header: 'Y75',
      width: '*',
      binding: 'y75',
      dataType: 'String',
    },
    {
      header: 'Y76',
      width: '*',
      binding: 'y76',
      dataType: 'String',
    },
    {
      header: 'Y77',
      width: '*',
      binding: 'y77',
      dataType: 'String',
    },
    {
      header: 'Y78',
      width: '*',
      binding: 'y78',
      dataType: 'String',
    },
    {
      header: 'Y79',
      width: '*',
      binding: 'y79',
      dataType: 'String',
    },
    {
      header: 'Y80',
      width: '*',
      binding: 'y80',
      dataType: 'String',
    },
    {
      header: 'Y81',
      width: '*',
      binding: 'y81',
      dataType: 'String',
    },
    {
      header: 'Y82',
      width: '*',
      binding: 'y82',
      dataType: 'String',
    },
    {
      header: 'Y83',
      width: '*',
      binding: 'y83',
      dataType: 'String',
    },
    {
      header: 'Y84',
      width: '*',
      binding: 'y84',
      dataType: 'String',
    },
    {
      header: 'Y85',
      width: '*',
      binding: 'y85',
      dataType: 'String',
    },
    {
      header: 'Y86',
      width: '*',
      binding: 'y86',
      dataType: 'String',
    },
    {
      header: 'Y87',
      width: '*',
      binding: 'y87',
      dataType: 'String',
    },
    {
      header: 'Y88',
      width: '*',
      binding: 'y88',
      dataType: 'String',
    },
    {
      header: 'Y89',
      width: '*',
      binding: 'y89',
      dataType: 'String',
    },
    {
      header: 'Y90',
      width: '*',
      binding: 'y90',
      dataType: 'String',
    },
    {
      header: 'Y91',
      width: '*',
      binding: 'y91',
      dataType: 'String',
    },
    {
      header: 'Y92',
      width: '*',
      binding: 'y92',
      dataType: 'String',
    },
    {
      header: 'Y93',
      width: '*',
      binding: 'y93',
      dataType: 'String',
    },
    {
      header: 'Y94',
      width: '*',
      binding: 'y94',
      dataType: 'String',
    },
    {
      header: 'Y95',
      width: '*',
      binding: 'y95',
      dataType: 'String',
    },
    {
      header: 'Y96',
      width: '*',
      binding: 'y96',
      dataType: 'String',
    },
    {
      header: 'Y97',
      width: '*',
      binding: 'y97',
      dataType: 'String',
    },
    {
      header: 'Y98',
      width: '*',
      binding: 'y98',
      dataType: 'String',
    },
    {
      header: 'Y99',
      width: '*',
      binding: 'y99',
      dataType: 'String',
    },
    {
      header: 'Y100',
      width: '*',
      binding: 'y100',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE1',
      width: '*',
      binding: 'contCode1',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE2',
      width: '*',
      binding: 'contCode2',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE3',
      width: '*',
      binding: 'contCode3',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE4',
      width: '*',
      binding: 'contCode4',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE5',
      width: '*',
      binding: 'contCode5',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE6',
      width: '*',
      binding: 'contCode6',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE7',
      width: '*',
      binding: 'contCode7',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE8',
      width: '*',
      binding: 'contCode8',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE9',
      width: '*',
      binding: 'contCode9',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE10',
      width: '*',
      binding: 'contCode10',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE11',
      width: '*',
      binding: 'contCode11',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE12',
      width: '*',
      binding: 'contCode12',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE13',
      width: '*',
      binding: 'contCode13',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE14',
      width: '*',
      binding: 'contCode14',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE15',
      width: '*',
      binding: 'contCode15',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE16',
      width: '*',
      binding: 'contCode16',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE17',
      width: '*',
      binding: 'contCode17',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE18',
      width: '*',
      binding: 'contCode18',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE19',
      width: '*',
      binding: 'contCode19',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE20',
      width: '*',
      binding: 'contCode20',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE21',
      width: '*',
      binding: 'contCode21',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE22',
      width: '*',
      binding: 'contCode22',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE23',
      width: '*',
      binding: 'contCode23',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE24',
      width: '*',
      binding: 'contCode24',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE25',
      width: '*',
      binding: 'contCode25',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE26',
      width: '*',
      binding: 'contCode26',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE27',
      width: '*',
      binding: 'contCode27',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE28',
      width: '*',
      binding: 'contCode28',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE29',
      width: '*',
      binding: 'contCode29',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE30',
      width: '*',
      binding: 'contCode30',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE31',
      width: '*',
      binding: 'contCode31',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE32',
      width: '*',
      binding: 'contCode32',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE33',
      width: '*',
      binding: 'contCode33',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE34',
      width: '*',
      binding: 'contCode34',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE35',
      width: '*',
      binding: 'contCode35',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE36',
      width: '*',
      binding: 'contCode36',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE37',
      width: '*',
      binding: 'contCode37',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE38',
      width: '*',
      binding: 'contCode38',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE39',
      width: '*',
      binding: 'contCode39',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE40',
      width: '*',
      binding: 'contCode40',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE41',
      width: '*',
      binding: 'contCode41',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE42',
      width: '*',
      binding: 'contCode42',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE43',
      width: '*',
      binding: 'contCode43',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE44',
      width: '*',
      binding: 'contCode44',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE45',
      width: '*',
      binding: 'contCode45',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE46',
      width: '*',
      binding: 'contCode46',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE47',
      width: '*',
      binding: 'contCode47',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE48',
      width: '*',
      binding: 'contCode48',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE49',
      width: '*',
      binding: 'contCode49',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE50',
      width: '*',
      binding: 'contCode50',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE51',
      width: '*',
      binding: 'contCode51',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE52',
      width: '*',
      binding: 'contCode52',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE53',
      width: '*',
      binding: 'contCode53',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE54',
      width: '*',
      binding: 'contCode54',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE55',
      width: '*',
      binding: 'contCode55',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE56',
      width: '*',
      binding: 'contCode56',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE57',
      width: '*',
      binding: 'contCode57',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE58',
      width: '*',
      binding: 'contCode58',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE59',
      width: '*',
      binding: 'contCode59',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE60',
      width: '*',
      binding: 'contCode60',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE61',
      width: '*',
      binding: 'contCode61',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE62',
      width: '*',
      binding: 'contCode62',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE63',
      width: '*',
      binding: 'contCode63',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE64',
      width: '*',
      binding: 'contCode64',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE65',
      width: '*',
      binding: 'contCode65',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE66',
      width: '*',
      binding: 'contCode66',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE67',
      width: '*',
      binding: 'contCode67',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE68',
      width: '*',
      binding: 'contCode68',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE69',
      width: '*',
      binding: 'contCode69',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE70',
      width: '*',
      binding: 'contCode70',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE71',
      width: '*',
      binding: 'contCode71',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE72',
      width: '*',
      binding: 'contCode72',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE73',
      width: '*',
      binding: 'contCode73',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE74',
      width: '*',
      binding: 'contCode74',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE75',
      width: '*',
      binding: 'contCode75',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE76',
      width: '*',
      binding: 'contCode76',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE77',
      width: '*',
      binding: 'contCode77',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE78',
      width: '*',
      binding: 'contCode78',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE79',
      width: '*',
      binding: 'contCode79',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE80',
      width: '*',
      binding: 'contCode80',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE81',
      width: '*',
      binding: 'contCode81',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE82',
      width: '*',
      binding: 'contCode82',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE83',
      width: '*',
      binding: 'contCode83',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE84',
      width: '*',
      binding: 'contCode84',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE85',
      width: '*',
      binding: 'contCode85',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE86',
      width: '*',
      binding: 'contCode86',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE87',
      width: '*',
      binding: 'contCode87',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE88',
      width: '*',
      binding: 'contCode88',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE89',
      width: '*',
      binding: 'contCode89',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE90',
      width: '*',
      binding: 'contCode90',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE91',
      width: '*',
      binding: 'contCode91',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE92',
      width: '*',
      binding: 'contCode92',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE93',
      width: '*',
      binding: 'contCode93',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE94',
      width: '*',
      binding: 'contCode94',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE95',
      width: '*',
      binding: 'contCode95',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE96',
      width: '*',
      binding: 'contCode96',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE97',
      width: '*',
      binding: 'contCode97',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE98',
      width: '*',
      binding: 'contCode98',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE99',
      width: '*',
      binding: 'contCode99',
      dataType: 'String',
    },
    {
      header: 'CONT_CODE100',
      width: '*',
      binding: 'contCode100',
      dataType: 'String',
    },
  ];
}

export const QSEAR_35_CONT_COLOR_CHART_N_HEADER_TREE: HeaderNode[] = [
  createLeafNode("matrCode", "내용물코드", "matrCode"),
  createLeafNode("matrName", "내용물명", "matrName"),
  createLeafNode("batchCnt", "로트 건수", "batchCnt"),
  createLeafNode("btnCancel", "삭제", "btnCancel"),
];
