import type { GridColumnDef } from "@/components/ap-wijmo/grid/GridTypes";
import {
  createGroupNode,
  createLeafNode,
  type HeaderNode,
} from "@/components/ap-wijmo/grid/HeaderTree";
import type { Qcdvm10NewitemRow } from "../types/Qcdvm10NewitemTypes";

export const createGrdNewitemListColumnDefinition = (): GridColumnDef<Qcdvm10NewitemRow>[] => {
  return [
    {
      header: '내용물코드',
      width: 80,
      binding: 'matrCode',
      dataType: 'String',
    },
    {
      header: '내용물명',
      width: 300,
      binding: 'matrName',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '발행일',
      width: 80,
      binding: 'rptDate',
      dataType: 'String',
    },
    {
      header: '연구원',
      width: 80,
      binding: 'researchUser',
      dataType: 'String',
    },
    {
      header: '제형',
      width: 200,
      binding: 'codeName',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '기능성',
      width: 90,
      binding: 'functionName',
      dataType: 'String',
    },
    {
      header: '성상',
      width: 200,
      binding: 'shapeText',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '신원료',
      width: 120,
      binding: 'newMatr',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '종합판정',
      width: 70,
      binding: 'resultFinalJudg',
      dataType: 'String',
    },
    {
      header: '혁신상품 특성분류',
      width: 70,
      binding: 'innoPrdCi',
      dataType: 'String',
    },
    {
      header: '사용 기한',
      width: 60,
      binding: 'useLimit',
      dataType: 'String',
    },
    {
      header: 'SAP 사용기한',
      width: 60,
      binding: 'sapUseLimit',
      dataType: 'String',
    },
    {
      header: '규격서',
      width: 50,
      binding: 'specYn',
      dataType: 'String',
    },
    {
      header: '4주 안정도',
      width: 50,
      binding: 'stabYn',
      dataType: 'String',
    },
    {
      header: 'Pilot',
      width: 50,
      binding: 'pilotSeq',
      dataType: 'String',
    },
    {
      header: '의뢰',
      width: 50,
      binding: 'stabReqCi',
      dataType: 'String',
    },
    {
      header: '일자',
      width: 80,
      binding: 'pilotDate',
      dataType: 'String',
    },
    {
      header: '구분',
      width: 60,
      binding: 'mnuType',
      dataType: 'String',
    },
    {
      header: '오더번호',
      width: 80,
      binding: 'mnuOrder',
      dataType: 'String',
    },
    {
      header: '제조번호',
      width: 80,
      binding: 'mnuNo',
      dataType: 'String',
    },
    {
      header: '익일판정',
      width: 80,
      binding: 'nextdayJudg',
      dataType: 'String',
    },
    {
      header: '1주차 안정도판정',
      width: '*',
      binding: 'wk1QmsPlotStabJudgCd',
      dataType: 'String',
      align: 'center',
    },
    {
      header: '안정도판정',
      width: 100,
      binding: 'stabJudg',
      dataType: 'String',
      align: 'center',
    },
    {
      header: 'MES 진행사항',
      width: 200,
      binding: 'etc',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '카운터',
      width: 250,
      binding: 'cnt',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '연계홋수',
      width: 70,
      binding: 'connMatrCode',
      dataType: 'String',
    },
    {
      header: '하위',
      width: 250,
      binding: 'downConnMatrCode',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '기능성 원료리스트',
      width: 250,
      binding: 'cmnt',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '제품특징',
      width: 500,
      binding: 'prdChar',
      dataType: 'String',
      align: 'left',
    },
    {
      header: '기타정보',
      width: 500,
      binding: 'etcInfo',
      dataType: 'String',
      align: 'left',
    },
  ];
}

export const QCDVM_10_NEWITEM_HEADER_TREE: HeaderNode[] = [
  createLeafNode("matrCode", "내용물코드", "matrCode"),
  createLeafNode("matrName", "내용물명", "matrName"),
  createLeafNode("rptDate", "발행일", "rptDate"),
  createLeafNode("researchUser", "연구원", "researchUser"),
  createLeafNode("codeName", "제형", "codeName"),
  createLeafNode("functionName", "기능성", "functionName"),
  createLeafNode("shapeText", "성상", "shapeText"),
  createLeafNode("newMatr", "신원료", "newMatr"),
  createLeafNode("resultFinalJudg", "종합판정", "resultFinalJudg"),
  createLeafNode("innoPrdCi", "혁신상품 특성분류", "innoPrdCi"),
  createLeafNode("useLimit", "사용 기한", "useLimit"),
  createLeafNode("sapUseLimit", "SAP 사용기한", "sapUseLimit"),
  createLeafNode("specYn", "규격서", "specYn"),
  createLeafNode("stabYn", "4주 안정도", "stabYn"),
  createGroupNode("pilotSeqGroup", "Pilot", [
    createLeafNode("pilotSeq", "차수", "pilotSeq"),
    createLeafNode("stabReqCi", "의뢰", "stabReqCi"),
    createLeafNode("pilotDate", "일자", "pilotDate"),
    createLeafNode("mnuType", "구분", "mnuType"),
    createLeafNode("mnuOrder", "오더번호", "mnuOrder"),
    createLeafNode("mnuNo", "제조번호", "mnuNo"),
    createLeafNode("nextdayJudg", "익일판정", "nextdayJudg"),
    createLeafNode("wk1QmsPlotStabJudgCd", "1주차 안정도판정", "wk1QmsPlotStabJudgCd"),
    createLeafNode("stabJudg", "안정도판정", "stabJudg"),
    createLeafNode("etc", "MES 진행사항", "etc"),
  ]),
  createLeafNode("cnt", "카운터", "cnt"),
  createGroupNode("connMatrCodeGroup", "연계홋수", [
    createLeafNode("connMatrCode", "상위", "connMatrCode"),
    createLeafNode("downConnMatrCode", "하위", "downConnMatrCode"),
  ]),
  createLeafNode("cmnt", "기능성 원료리스트", "cmnt"),
  createLeafNode("prdChar", "제품특징", "prdChar"),
  createLeafNode("etcInfo", "기타정보", "etcInfo"),
];
